/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jni_JNIexample */

#ifndef _Included_com_example_jni_JNIexample
#define _Included_com_example_jni_JNIexample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jni_JNIexample
 * Method:    increment
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_jni_JNIexample_increment
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
