/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ognjen_stojisavljevic_memorygame_JNI */

#ifndef _Included_ognjen_stojisavljevic_memorygame_JNI
#define _Included_ognjen_stojisavljevic_memorygame_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ognjen_stojisavljevic_memorygame_JNI
 * Method:    increment
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_ognjen_stojisavljevic_memorygame_JNI_increment
  (JNIEnv *, jobject, jint);

/*
 * Class:     ognjen_stojisavljevic_memorygame_JNI
 * Method:    decrement
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_ognjen_stojisavljevic_memorygame_JNI_decrement
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
